from src.constant import *
import os,sys

# 1. Data Inngestion

ROOT_DIR = ROOT_DIR_KEY

 # Dataset_url = 

DATA_PATH = os.path.join(ROOT_DIR,DATA_DIR,DATA_DIR_KEY)
## So by this way we are geting our dataset path

RAW_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,CURRENT_TIME_STAMP,
                             DATA_INGESTION_RAW_DATA_DIR,RAW_DATA_DIR_KEY)


TRAIN_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,
                               CURRENT_TIME_STAMP,DATA_INGESTION_INGESTED_DATA_DIR_KEY,TRAIN_DATA_DIR_KEY)


TEST_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,
                               CURRENT_TIME_STAMP,DATA_INGESTION_INGESTED_DATA_DIR_KEY,TEST_DATA_DIR_KEY)


# 2. Data Transformation

PREPROCESSING_OBJ_FILE = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                      DATA_PREPROCESS_DIR,DATA_PROCESSING_OBJ)

TRANSFORM_TRAIN_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                         DATA_TRANSFORMATION_DIR,TRANSFORM_TRAIN_DIR_KEY)

TRANSFORM_TEST_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                         DATA_TRANSFORMATION_DIR,TRANSFORM_TEST_DIR_KEY)

FEATURE_ENGINEERING_OBJ_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                                 DATA_PREPROCESS_DIR,'feature_engg.pkl')



# 3 . Model Training

MODEL_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,MODEL_TRAINER_KEY,MODEL_OBJECT)

